configs/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from main.views import not_found_error, internal_server_error

handler404 = 'main.views.not_found_error'
handler500 = 'main.views.internal_server_error'

admin.site.site_header = "Roomio Gateway Admin"
admin.site.site_title = "Roomio Gateway Admin"
admin.site.index_title = "Welcome to Roomio Gateway Admin"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('_nested_admin/', include('nested_admin.urls')),
    path('', include('main.urls', namespace='main')),
]

main/urls.py
from django.urls import path
from .views import SignUpView, SignInView, EditorView, PushRequest, StateRequest

app_name = 'main'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', SignInView.as_view(), name='login'),
    path('editor/', EditorView.as_view(), name='editor'),
    path('push.php/', PushRequest.as_view(), name='push'),
    path('state.php/', StateRequest.as_view(), name='state'),
]

main/models.py
from django.db import models
from .choices import LOGGING_LEVEL


class SingletonModel(models.Model):
    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.pk = 1
        super(SingletonModel, self).save(*args, **kwargs)

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(pk=1)
        return obj


class Server(SingletonModel):
    name = models.CharField(max_length=200, default='Roomio Server')
    method = models.CharField(max_length=50, default='tcp')
    app_host = models.GenericIPAddressField(default='0.0.0.0')
    app_port = models.IntegerField(default=1880)
    timeout = models.IntegerField(default=2)
    max_log_days = models.IntegerField(default=3)
    logging = models.CharField(max_length=50, choices=LOGGING_LEVEL, default=LOGGING_LEVEL[0][0])
    check_modbus_interval = models.IntegerField(default=60)
    check_modbus_interval_after_failed_attempt = models.IntegerField(default=120)


class Device(models.Model):
    device_name = models.CharField(max_length=200)
    hrc_ip = models.GenericIPAddressField()
    hrc_port = models.IntegerField()
    unit_id = models.IntegerField()
    device_template_id = models.IntegerField()
    room = models.IntegerField()
    server = models.ForeignKey(Server, on_delete=models.CASCADE, related_name='devices')


class Scene(models.Model):
    name = models.CharField(max_length=200)
    device = models.ForeignKey(Device, on_delete=models.CASCADE, related_name='scenes')


class DeviceLocation(models.Model):
    device_location = models.CharField(max_length=200)
    device = models.ForeignKey(Device, on_delete=models.CASCADE, related_name='device_locations')


class Tag(models.Model):
    modbus_id = models.IntegerField()
    device_location = models.ForeignKey(DeviceLocation, on_delete=models.CASCADE, related_name='tags')


class TagsAndValue(models.Model):
    modbus_id = models.IntegerField()
    value = models.IntegerField()
    scene = models.ForeignKey(Scene, on_delete=models.CASCADE, related_name='tags_and_values')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Roomio Gateway - {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block stylesheet %}
    {% endblock stylesheet %}
</head>

<body>

{% block content %}
{% endblock content %}

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
{% block script %}
{% endblock script %}
</body>
</html>

templates/editor.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Editor{% endblock title %}
{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/editor.css' %}">
{% endblock stylesheet %}

{% block content %}
  <div class="container editor-form">
    <h3>Server settings</h3>
    <form method="post">
      {% csrf_token %}
      {% if form.errors %}
        <ul>
          <div class="alert alert-danger">
            {% for field in form %}
              {% for error in field.errors %}
                <li><strong>{{ field.label }}:</strong> {{ error|escape }}</li>
              {% endfor %}
            {% endfor %}
            {% for form in device_formset %}
              {% for field in field.errors %}
                {% for error in field.errors %}
                  <li><strong>{{ field.label }}:</strong> {{ error|escape }}</li>
                {% endfor %}
              {% endfor %}
            {% endfor %}
          </div>
        </ul>
      {% endif %}

      <div class="serverNamePart">
        <div class="form-group serverNamePart">
          <label for="id_name">Server name</label>
          <input type="text" class="form-control" id="id_name" name="name"
                 value="{{ form.name.value|default_if_none:'' }}">
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="id_app_host">Rest server IP</label>
            <input type="text" class="form-control" id="id_app_host" name="app_host" value="0.0.0.0">
            <small class="form-text text-muted">Use 0.0.0.0 for access from all connected networks</small>
          </div>
          <div class="form-group col-md-2">
            <label for="id_app_port">Rest server port</label>
            <input type="number" class="form-control" id="id_app_port" name="app_port" value="1880">
            <small class="form-text text-muted">Port to rest request</small>
          </div>
          <div class="form-group col-md-4">
            <label for="id_logging">Log level</label>
            <select id="id_logging" name="logging" class="form-control">
              <option selected>INFO</option>
              <option>DEBUG</option>
            </select>
            <small class="form-text text-muted">Debug only for debugging</small>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-4">
            <label for="id_timeout">Timeout</label>
            <input type="number" class="form-control" id="id_timeout" name="timeout" value="3">
            <small class="form-text text-muted">Timeout in seconds for connecting to Modbus server</small>
          </div>
          <div class="form-group col-md-4">
            <label for="id_check_modbus_interval">Check modbus interval</label>
            <input type="number" class="form-control" id="id_check_modbus_interval"
                   name="check_modbus_interval" value="3">
            <small class="form-text text-muted">Period in seconds for check the modbus server
              available</small>
          </div>
          <div class="form-group col-md-4">
            <label for="id_check_modbus_interval_after_failed_attempt">Check modbus interval after
              fail</label>
            <input type="number" class="form-control" id="id_check_modbus_interval_after_failed_attempt"
                   name="check_modbus_interval_after_failed_attempt" value="3">
            <small class="form-text text-muted">
              A period in seconds for waiting to connect to the modbus server after failed connect attempt
            </small>
          </div>
        </div>
      </div>

      <div id="device_formset">
        {{ device_formset.management_form }}
        <div class="dynamic-form device-formset" id="device_form_template" style="display: none;">
          <div class="devicePart">
            <h4>Devices</h4>
            <div class="form-row">
              <div class="form-group col-md-2">
                <label for="id_device_name">Modbus server name</label>
                <input type="text" class="form-control" id="id_device_name" name="device_name">
              </div>
              <div class="form-group col-md-2">
                <label for="id_hrc_ip">Modbus address</label>
                <input type="text" class="form-control" id="id_hrc_ip" name="hrc_ip" placeholder="0.0.0.0">
                <small class="form-text text-muted">Hostname/IP address of Modbus server</small>
              </div>
              <div class="form-group col-md-2">
                <label for="id_hrc_port">Modbus port</label>
                <input type="number" class="form-control" id="id_hrc_port" name="hrc_port" placeholder="1880">
                <small class="form-text text-muted">Port of Modbus server for connect</small>
              </div>
              <div class="form-group col-md-2">
                <label for="id_unit_id">Unit ID</label>
                <input type="number" class="form-control" id="id_unit_id" name="unit_id">
                <small class="form-text text-muted">ID of current slave on Modbus</small>
              </div>
              <div class="form-group col-md-2">
                <label for="id_device_template_id">Modbus device template</label>
                <input type="number" class="form-control" id="id_device_template_id" name="device_template_id">
                <small class="form-text text-muted">ID of modbus template</small>
              </div>
              <div class="form-group col-md-2">
                <label for="id_room">Room</label>
                <input type="number" class="form-control" id="id_room" name="room">
                <small class="form-text text-muted">The room number that the device controls</small>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="deviceLocationPart col">
              <h4>Device locations</h4>
              <div class="form-group">
                <label for="locationNameInput">Location name</label>
                <input type="text" class="form-control" id="locationNameInput">
              </div>
            </div>
            <div class="tagPart col">
              <h4>Tags</h4>
              <div class="form-group">
                <label for="modbusIDTagsInput">Modbus ID</label>
                <input type="number" class="form-control" id="modbusIDTagsInput">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="scenePart col">
              <h4>Scenes</h4>
              <div class="form-group">
                <label for="sceneNameInput">Scene name</label>
                <input type="text" class="form-control" id="sceneNameInput">
              </div>
            </div>
            <div class="tagAndValuesPart col">
              <h4>Tags and Values</h4>
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="modbusIDTagsValuesInput">Modbus ID</label>
                  <input type="number" class="form-control" id="modbusIDTagsValuesInput">
                </div>
                <div class="form-group col-md-6">
                  <label for="valueInput">Value</label>
                  <input type="number" class="form-control" id="valueInput">
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
      <button type="submit" class="btn btn-primary">Save</button>
    </form>
  </div>
{% endblock content %}

{% block script %}
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="{% static 'js/jquery.formset.js' %}"></script>
  <script src="{% static 'js/editor.js' %}"></script>
{% endblock script %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login{% endblock title %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock stylesheet %}

{% block content %}
    <div class="login-form">
        <form method="post">
            {% csrf_token %}
            <h2 class="text-center">Log in</h2>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Username"
                       required="required" name="username" id="id_username">
                {% if form.username.errors %}
                    <div class="alert alert-danger">
                        {{ form.username.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="Password"
                       required="required" name="password" id="id_password">
                {% if form.password.errors %}
                    <div class="alert alert-danger">
                        {{ form.password.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                {% if form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
                <button type="submit" class="btn btn-primary btn-block">Login</button>
            </div>
            <div class="clearfix">
                <p class="text-center">Not registered? <a href="{% url 'main:signup' %}">Create an account</a></p>
            </div>
        </form>
    </div>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Sign up{% endblock title %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock stylesheet %}

{% block content %}
    <div class="login-form">
        <form method="post">
            {% csrf_token %}
            <h2 class="text-center">Sign up</h2>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Username"
                       required="required" name="username" id="id_username">
                {% if form.username.errors %}
                    <div class="alert alert-danger">
                        {{ form.username.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="Choose password"
                       required="required" name="password" id="id_password">
                {% if form.password1.errors %}
                    <div class="alert alert-danger">
                        {{ form.password1.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="Confirm password"
                       required="required" name="password2" id="id_password2">
                {% if form.password2.errors %}
                    <div class="alert alert-danger">
                        {{ form.password2.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block">Sign up</button>
            </div>
            <div class="clearfix">
                <p class="text-center">Already a member? <a href="{% url 'main:login' %}">Log in</a></p>
            </div>
        </form>
    </div>
{% endblock content %}